// The handoff: the prompt hook that records where the transcript is, the
// reading the skill's preamble runs off it, and the switch hook that turns a
// standing "Switch model" answer into the go. All run through the launcher,
// the exact command `hooks.json` and the skill run, against transcripts
// written line by line the way Claude Code writes them.
//
// What is asserted is which situations produce a reading or a go and which
// stay silent; the wording of either is read by a session, not by a test.
// The one wording the tests do hold is the header and labels the switch
// hook matches, which the skill text has to carry verbatim.
import assert from "node:assert/strict";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import {
	dataDir,
	fixtureDir,
	type Result,
	runHook,
	runtimes,
} from "../../../tests/harness.mts";
import { BRIEF, FORK, HANDOFF_HEADER, SWITCH } from "../lib/handoff.mts";

const PLUGIN = join(fileURLToPath(new URL(".", import.meta.url)), "..");

const LAUNCHER = join(PLUGIN, "lib", "shared", "launch.mjs");

// Spelled out rather than imported, so a record that moves fails a test
// instead of taking the tests with it.
const RECORD_DIR = "claude-den-session";

const QUESTION = "How should the implementation be handed off?";

const turn = (tokens: number, extra: Record<string, unknown> = {}) => ({
	type: "assistant",
	message: {
		model: "claude-fable-5-1",
		usage: { input_tokens: 32, cache_read_input_tokens: tokens - 32 },
	},
	...extra,
});

const typed = (text: string, extra: Record<string, unknown> = {}) => ({
	type: "user",
	message: { role: "user", content: text },
	...extra,
});

/** A tool result Claude Code wrote under the user role: not something typed. */
const toolResult = () => ({
	type: "user",
	message: {
		role: "user",
		content: [{ type: "tool_result", content: "ok", tool_use_id: "t" }],
	},
	toolUseResult: "ok",
});

const answered = (header: string, label: string) => ({
	type: "user",
	message: {
		role: "user",
		content: [{ type: "tool_result", content: "answered", tool_use_id: "q" }],
	},
	toolUseResult: {
		questions: [
			{ question: QUESTION, header, options: [], multiSelect: false },
		],
		answers: { [QUESTION]: label },
		annotations: {},
	},
});

const compaction = () => ({ type: "system", subtype: "compact_boundary" });

/**
 * A background task finishing: Claude Code appends its notice under the user
 * role as string content, with `promptSource: "system"`, or `"sdk"` when the
 * session is driven through the SDK.
 */
const notification = (source = "system") => ({
	type: "user",
	promptSource: source,
	message: {
		role: "user",
		content:
			"<task-notification>\n<task-id>a1</task-id>\n<status>completed</status>\n</task-notification>",
	},
});

/** A slash command as typed, with whatever followed its name as its args. */
const command = (name: string, args: string, meta = false) => ({
	type: "user",
	...(meta ? { isMeta: true } : {}),
	message: {
		role: "user",
		content: `<command-name>${name}</command-name>\n            <command-message>${name.slice(1)}</command-message>\n            <command-args>${args}</command-args>`,
	},
});

/**
 * What `/model opus` leaves on the transcript: the command as a user entry
 * with string content, then its output, which 2.1.266 writes as a
 * `local_command` system entry and earlier builds wrote as a second user
 * entry. Both shapes are here, with the caveat line a resumed session gets.
 */
const modelCommand = () => [
	typed(
		"<command-name>/model</command-name>\n            <command-message>model</command-message>\n            <command-args>opus</command-args>",
	),
	{
		type: "system",
		subtype: "local_command",
		content: "<local-command-stdout>Set model to Opus 5</local-command-stdout>",
		level: "info",
	},
	typed("<local-command-stdout>Set model to Opus 5</local-command-stdout>"),
	typed(
		"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>",
	),
];

function transcript(dir: string, entries: readonly unknown[]): string {
	const path = join(dir, "session.jsonl");

	writeFileSync(path, `${entries.map((e) => JSON.stringify(e)).join("\n")}\n`);

	return path;
}

function ok(result: Result): string {
	assert.equal(result.status, 0, result.stderr);

	return result.stdout;
}

test("the skill text carries the header and labels the switch hook matches", () => {
	const skill = readFileSync(
		join(PLUGIN, "skills", "handoff-cost", "SKILL.md"),
		"utf8",
	);
	const lead = readFileSync(join(PLUGIN, "skills", "lead", "SKILL.md"), "utf8");

	for (const literal of [HANDOFF_HEADER, FORK, SWITCH, BRIEF]) {
		assert.ok(skill.includes(`\`${literal}\``), literal);
	}

	assert.ok(lead.includes(`\`${SWITCH}\``), SWITCH);
	assert.ok(lead.includes(HANDOFF_HEADER), HANDOFF_HEADER);
});

for (const runtime of runtimes()) {
	const data = dataDir(runtime);
	const name = (what: string) => `${runtime}: ${what}`;
	const run = (temp: string, argv: readonly string[], input: unknown) =>
		runHook({ launcher: LAUNCHER, data, temp, argv, input });

	const record = (temp: string, session: string, path: string) =>
		run(temp, ["hooks/transcript-record"], {
			hook_event_name: "UserPromptSubmit",
			session_id: session,
			transcript_path: path,
			prompt: "carry on",
		});

	const reading = (temp: string, session: string) =>
		ok(
			run(
				temp,
				["scripts/handoff-cost", "--session", session, "--target", "opus"],
				{},
			),
		);

	const switched = (temp: string, path: string, extra = {}) =>
		run(temp, ["hooks/handoff-switch"], {
			hook_event_name: "PostModelSwitch",
			session_id: "s",
			transcript_path: path,
			from_model: "claude-fable-5-1",
			to_model: "claude-opus-5",
			source: "command",
			...extra,
		});

	test(
		name("a prompt records the transcript, and a subagent's does not"),
		() => {
			const temp = fixtureDir("record");
			const path = transcript(temp, [turn(1000)]);

			assert.equal(ok(record(temp, "main", path)), "");
			assert.deepEqual(
				JSON.parse(readFileSync(join(temp, RECORD_DIR, "main.json"), "utf8")),
				{ transcript_path: path },
			);

			ok(
				run(temp, ["hooks/transcript-record"], {
					hook_event_name: "UserPromptSubmit",
					session_id: "sub",
					agent_id: "agent-1",
					transcript_path: path,
				}),
			);
			assert.throws(() => readFileSync(join(temp, RECORD_DIR, "sub.json")));
		},
	);

	test(name("the reading prices the newest main-session turn"), () => {
		const temp = fixtureDir("reading");
		const path = transcript(temp, [
			turn(90_000),
			typed("go on"),
			turn(110_532),
			toolResult(),
			// A subagent's turn sharing the transcript is not the session's.
			turn(5_000, { isSidechain: true }),
		]);

		ok(record(temp, "s", path));

		const text = reading(temp, "s");

		assert.ok(text.includes("110,532 tokens on claude-fable-5-1"), text);
		assert.ok(text.includes(`${SWITCH} (to opus): cache miss 110,532`), text);
		assert.ok(text.includes(`${FORK} (stays on claude-fable-5-1)`), text);
		assert.ok(!text.includes("$"), text);
		// Whether the original model's cache is still warm by then is unknown
		// here, so the reading prices the switch and nothing after it.
		assert.ok(!text.includes("Switching back"), text);
	});

	test(
		name("the reading says when the session is already on the target"),
		() => {
			const temp = fixtureDir("reading-same");
			const path = transcript(temp, [
				{
					type: "assistant",
					message: {
						model: "claude-opus-5",
						usage: { input_tokens: 32, cache_read_input_tokens: 9_968 },
					},
				},
			]);

			ok(record(temp, "s", path));

			const text = reading(temp, "s");

			assert.ok(
				text.includes(`${SWITCH} (to opus): already on claude-opus-5`),
				text,
			);
			assert.ok(!text.includes("cache miss 10,000"), text);
		},
	);

	test(name("a target that names no model is priced as the default"), () => {
		const temp = fixtureDir("reading-target");
		const path = transcript(temp, [turn(10_000)]);

		ok(record(temp, "s", path));

		const text = ok(
			run(
				temp,
				["scripts/handoff-cost", "--session", "s", "--target", "5"],
				{},
			),
		);

		assert.ok(!text.includes("already on"), text);
		assert.ok(text.includes(`${SWITCH} (to opus)`), text);
		assert.ok(text.includes('"5"'), text);
	});

	test(
		name("the reading is unpriced after a compaction or with no record"),
		() => {
			const temp = fixtureDir("unpriced");
			const path = transcript(temp, [turn(110_532), compaction()]);

			ok(record(temp, "s", path));

			const compacted = reading(temp, "s");

			assert.ok(compacted.includes("Context size unknown"), compacted);
			assert.ok(!compacted.includes("110,532"), compacted);
			assert.ok(compacted.includes(SWITCH), compacted);

			const unrecorded = reading(temp, "never-prompted");

			assert.ok(unrecorded.includes("Context size unknown"), unrecorded);
			assert.ok(unrecorded.includes("no transcript is recorded"), unrecorded);
		},
	);

	test(name("a switch on a standing Switch answer is the go"), () => {
		const temp = fixtureDir("switch-go");
		const path = transcript(temp, [
			turn(1000),
			answered(HANDOFF_HEADER, SWITCH),
			turn(1100),
			toolResult(),
			// A background agent finishing in the meantime is written under
			// the user role too, and is not the user typing either, whichever
			// way the session is driven.
			notification(),
			notification("sdk"),
			// What /model leaves on the transcript, when it has landed by the
			// time the hook reads the tail; it is not the user typing.
			...modelCommand(),
		]);

		const text = ok(switched(temp, path));

		assert.ok(text.includes("claude-opus-5"), text);
		assert.ok(text.includes(SWITCH), text);

		// The picker is the other way a person switches.
		assert.ok(ok(switched(temp, path, { source: "picker" })).includes(SWITCH));

		// The command's entry is written after the switch event fires, so the
		// go does not wait for it: the answer standing is enough, whichever
		// way the switch was made.
		const bare = transcript(temp, [
			answered(HANDOFF_HEADER, SWITCH),
			turn(1100),
		]);

		assert.ok(ok(switched(temp, bare)).includes(SWITCH));
		assert.ok(ok(switched(temp, bare, { source: "picker" })).includes(SWITCH));
	});

	test(name("a label with a suffix is still the Switch answer"), () => {
		const temp = fixtureDir("switch-suffix");
		const path = transcript(temp, [
			answered(HANDOFF_HEADER, `${SWITCH} (Recommended)`),
			turn(1100),
			...modelCommand(),
		]);

		assert.ok(ok(switched(temp, path)).includes(SWITCH));
	});

	test(
		name("an SDK-driven session's typed prompt overtakes the answer too"),
		() => {
			const temp = fixtureDir("switch-sdk-typed");
			const path = transcript(temp, [
				answered(HANDOFF_HEADER, SWITCH),
				turn(1100),
				typed("actually, wait", { promptSource: "sdk" }),
				turn(1200),
				...modelCommand(),
			]);

			assert.equal(ok(switched(temp, path)), "");
		},
	);

	test(
		name("a switch the user did not make is silent, answer or no answer"),
		() => {
			const temp = fixtureDir("switch-source");
			const path = transcript(temp, [
				answered(HANDOFF_HEADER, SWITCH),
				turn(1100),
			]);

			// A resume restores the model the user was leaving; an auto switch
			// is the harness's. Neither is the user carrying the answer out.
			assert.equal(ok(switched(temp, path, { source: "resume" })), "");
			assert.equal(ok(switched(temp, path, { source: "auto" })), "");
			assert.equal(ok(switched(temp, path, { source: "sdk" })), "");
			assert.equal(ok(switched(temp, path, { source: undefined })), "");
		},
	);

	test(
		name("a switch is silent once the user has typed since the answer"),
		() => {
			const temp = fixtureDir("switch-typed");
			const path = transcript(temp, [
				answered(HANDOFF_HEADER, SWITCH),
				turn(1100),
				typed("actually, wait"),
				turn(1200),
			]);

			assert.equal(ok(switched(temp, path)), "");
		},
	);

	test(
		name("a command carrying words the user typed overtakes the answer"),
		() => {
			const temp = fixtureDir("switch-command-args");
			const worded = transcript(temp, [
				answered(HANDOFF_HEADER, SWITCH),
				turn(1100),
				command("/den:lead", "drop the second row", true),
				turn(1200),
			]);

			assert.equal(ok(switched(temp, worded)), "");

			// The same command with nothing after its name is not the user
			// saying anything, and neither is /model with its argument.
			const bare = transcript(temp, [
				answered(HANDOFF_HEADER, SWITCH),
				turn(1100),
				command("/den:lead", ""),
				turn(1200),
				command("/model", "opus"),
			]);

			assert.ok(ok(switched(temp, bare)).includes(SWITCH));
		},
	);

	test(name("a switch is silent on a Fork answer or another question"), () => {
		const temp = fixtureDir("switch-other");

		assert.equal(
			ok(switched(temp, transcript(temp, [answered(HANDOFF_HEADER, FORK)]))),
			"",
		);
		assert.equal(
			ok(
				switched(
					temp,
					transcript(temp, [
						answered(HANDOFF_HEADER, SWITCH),
						turn(1100),
						answered("Library", "left-pad"),
						turn(1200),
					]),
				),
			),
			"",
		);
		assert.equal(
			ok(
				switched(
					temp,
					transcript(temp, [answered(HANDOFF_HEADER, SWITCH), compaction()]),
				),
			),
			"",
		);
	});

	test(
		name("a switch is silent for a subagent and for a missing transcript"),
		() => {
			const temp = fixtureDir("switch-silent");
			const path = transcript(temp, [answered(HANDOFF_HEADER, SWITCH)]);

			assert.equal(ok(switched(temp, path, { agent_id: "agent-1" })), "");
			assert.equal(ok(switched(temp, join(temp, "gone.jsonl"))), "");
		},
	);
}
